
data_dir = '/home/mehrdad/PycharmProjects/imSitu_vqa_baseline/data/'
img_dir = '/home/mehrdad/PycharmProjects/imSitu/resized_256/of500_images_resized/'

q_type_csv_file = 'role_qtype_map.csv'
r_class_csv_file = 'general_semantic_class.csv'
spec_data = 'imsitu_space.json'
vocabulary_file = 'vocabulary.json'
img_features_file = 'imSitu_vgg_features.json'
img_features_h5_file = 'imSitu_vgg_features.h5'
qa_template_file = 'qa_templates.json'
qa_dataset_file = 'qa_dataset.h5'
role_asnwer_frequency_file = 'role_asnwer_frequency.json'
abstracts_file = 'abstracts.txt'
roles_and_top1000ans_file = 'roles_and_top1000ans.json'
glove_path = 'glove/glove.6B.300d.txt'
experiment_multi = 'multi/'
priors = 'priors/'
wups='wups/'
experiment_multi_2 = 'multi_2/'
experiment_baseline = 'baseline/'
model_weights_file = 'model_weights.h5'
attention_model_weights_file = 'att_model_weights.h5'
ckpt_model_weights_file = 'ckpts/model_weights.h5'

predictions_file_name = 'predictions.txt'
answers_file_name = 'answers.txt'
roles_file_name = 'roles.txt'

answer_role_freq_file = 'answer_role_freq.json'